Vagrant.configure("2") do |config|
  config.vm.define "kubernetescluster" do |vm1|
    config.ssh.private_key_path = ["/Users/winpaing/Desktop/Kubernetes_Local_Lab/Setup/.ssh/kubernetes_local_setup_rsa"]
    config.ssh.forward_agent = true
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    
    # Set a valid hostname (using hyphens instead of underscores)
    vm1.vm.hostname = "kubernetes-local-setup"
    vm1.vm.box = "bento/ubuntu-22.04"
    vm1.vm.network "private_network", ip: "192.168.58.40", name: "vboxnet0"
    
    #vm1.vm.synced_folder ".", "/home/vagrant", type: "virtualbox"
    vm1.vm.synced_folder "/Users/winpaing/Desktop/Kubernetes_Local_Lab", "/home/vagrant", type: "virtualbox"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "kubernetes-local-setup"
      vb.memory = "8192"
      vb.cpus = 4
      vb.gui = false
    end

    vm1.vm.provision "shell", run: "always", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install vim net-tools zip curl jq tree unzip wget siege apt-transport-https ca-certificates software-properties-common -y
      netstat -tunlp
      echo "Hello from Kubernetes local Setup"
    SHELL

    vm1.vm.provision "shell", privileged: true, path: './scripts/docker-install.sh'
    vm1.vm.provision "shell", privileged: true, path: './scripts/kubectl-install.sh'
    vm1.vm.provision "shell", privileged: true, path: './scripts/kind-install.sh'
    vm1.vm.provision "shell", privileged: true, path: './scripts/helm-install.sh'
  end
end
